= John Doe - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: OneBook
OneBook is a desktop Address Book application. It uses a Graphical User Interface (GUI) but most of the interactions happen using Command Line Interface (CLI).

OneBook is optimized for companies' usage. It is also suitable for general usage.

OneBook allows users to easily import and export contacts, send emails conveniently and stores a database of contacts.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]]

=== Enhancement Added: Recycle Bin

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=bin]

#End of Extract#

---

==== Justification

Accidentally deleting contacts can be a major problem for companies expecially if it is an important contact.
The `undo` function is sometimes not suitable for use due to reasons such as:

* Many commands to undo.
* Application has already been closed and restarted, hence clearing the undo/redo stack.

The `restore` command allows users to selectively restore deleted contacts. +
The `bindelete` command allows users to manage their Recycle Bin to reduce clutter.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=bin]

#End of Extract#

---

=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}
